### ISSUE TITLE
Unable to create TOML configuration from stream

### ISSUE THREAD

**Issue by pgolinski** [dezhidki/Tommy#32]
Microsoft provided API for reading from stream, but Tommy doesn't use it.  I tried to add it to my project with minimal effort:

```csharp
public class TomlStreamSource : StreamConfigurationSource
{
    public TomlStreamSource(Stream stream)
    {
        Stream = stream;
    }

    public override IConfigurationProvider Build(IConfigurationBuilder builder)
    {
        return new TomlStreamConfigurationProvider(this);
    }
}

public class TomlStreamConfigurationProvider : StreamConfigurationProvider
{
    public TomlStreamConfigurationProvider(StreamConfigurationSource source) : base(source)
    {
    }

    public override void Load(Stream stream)
    {
        try
        {
            Data = TomlConfigurationFileParser.Parse(stream);
        }
        catch (TomlParseException e)
        {
            throw new FormatException("Could not parse the TOML stream.", e);
        }
    }
}

public static class ConfigurationBuilderExtensions
{
   public static IConfigurationBuilder AddTomlStream(
      this IConfigurationBuilder builder,
      Stream stream)
  {
      return builder.Add(new TomlStreamSource(stream));
  }
}
```

It should work except it won't as the TomlConfigurationFileParser class is internal. Is there a reason for that?

**Comment by dezhidki** [comment]
Hi!

Sorry for the late answer! `TomlConfigurationFileParser` was changed to `internal` in #22 by @bugproof as the reference implementation of [Microsoft.Extensions.Configuration.Json](https://github.com/dotnet/runtime/tree/main/src/libraries/Microsoft.Extensions.Configuration.Json/src) suggests doing the same.

Instead, `TomlStreamConfigurationProvider` and `TomlStreamConfigurationSource` you show should be part of core `Tommy.Extensions.Configuration` package. I'll add these to the package and close the issue once it's done. Alternatively, you can also submit your additions as a pull request if you want since you already have the classes implemented.

**Comment by pgolinski** [comment]
Hello!

I'd love to do it myself, but I can't tell when I will have some spare time. It requires some additional work for sake of consistency. Although there is no hurry as this feature is not most requested, so you can leave it to me if you want.

**Comment by bugproof** [comment]
Done in PR #34
