### ISSUE TITLE
I have found problems with double backslashes

### ISSUE THREAD

**Issue by MarcoRedred** [dezhidki/Tommy#8]
If a value contains double backslashes, the writing to the file is incorrect. To correct the problem I changed the function "Escape" like this:
```cs
case '\\':
 stringBuilder.Append(@"\\");  // Aggiunta la seconda barra da Marco
 break;
```

If a value ends with double backslashes, the reading is incorrect. To correct the problem I changed the function "ProcessQuotedValueCharacter" like this:
```cs
if (isNonLiteral && c == TomlSyntax.ESCAPE_SYMBOL)
  //if (next >= 0 && (char) next == quote) // Linea eliminata da Marco
     escaped = true;
```

If there is no newline at the end of the file, the last value remains dirty. To correct the problem I changed the function "ToTomlString" like this:

```cs
if (sectionableItems.Count == 0)
{
  tw.Flush();  // Line aggiunta da Marco
  return;
}
```

I'm probably not following the correct path to reporting bugs, but I'm new to github and don't understand English. So I apologize.
Ciao

**Comment by dezhidki** [comment]
Thanks for the reports!

I added the fixes and some basics unit tests regarding the first two problems.

As for the `Flush`, it's a bit more complicated: while flushing is something that `TextWriter` API provides, it is not always needed. For instance, it's usually needed if you are using `StreamTextWriter` with a stream for which you haven't enabled autoflushing (or for which it's not needed). 

Because flushing itself can be quite an expensive operation, I think it's best to leave it to Tommy user to flush the writer if they need to after all writing is completed, like so for example
```cs
using var writer = new StreamWriter(File.OpenWrite("out.toml"))
toml.WriteTo(writer);
// Flush at the end after all tables and subtables have been written
writer.Flush();
```

Because of that, I simply added a reminder of this into README.
